### PR TITLE
Includes with relative path & other minor improvements

### PR DESCRIPTION
**Pull request by martin-s-a**
```
/home/msalinas/Documents/standalone-installations/cifParsers/libcifpp/src/pdb/cif2pdb.cpp: In function ‘std::tuple<int, int> cif::pdb::WriteCoordinatesForModel(std::ostream&, const cif::datablock&, const std::map<std::__cxx11::basic_string<char>, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::set<std::__cxx11::basic_string<char> >&, int)’:
/home/msalinas/Documents/standalone-installations/cifParsers/libcifpp/src/pdb/cif2pdb.cpp:3362:15: warning: unused variable ‘pdbx_nonpoly_scheme’ [-Wunused-variable]
 3362 |         auto &pdbx_nonpoly_scheme = db["pdbx_nonpoly_scheme"];
      |         
```
This warning appeared while compiling the library. The use of that variable below has been commented, so I think it's appropiate to do the same thing with the unused variable.

Edit: Now I also modified the includes inside the `includes` folder. This is done to support local usage of this library without the need of installing the library system-wide (which supports multiple instances of different versions used each one by a different piece of software). System wide installations should remain unaffected by this change.

### CODE REVIEW

**Comment by mhekkel** [comment]
Good point, thanks for this. I did some more changes on your patch and merged it into trunk

**Comment by martin-s-a** [comment]
@mhekkel I am now having issues with those extra changes.
```
/home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/include/cif++/utilities.hpp:29:10: fatal error: cif++/exports.hpp: No such file or directory
   29 | #include "cif++/exports.hpp"
      |          ^~~~~~~~~~~~~~~~~~~
```
This is because `exports.hpp` is located in `./` relative to the file trying to include it, that's why in my PR I did not include the `cif++/`. If you wanted to use it in a system-wide installation format, `<cif++/exports.hpp>` is the way to go, but that, even if changed to `" "`, does not get along with relative path access.
I would recommend removing `"cif++/`, because it won't mess with system-wide installations, since it will locally find the `exports.hpp` with the relative path instead of retrieving the same file after converting the system-wide format to a path in `LD_LIBRARY_PATH`.

**Comment by mhekkel** [comment]
If you want to use the library on another location, you should still use the cmake --install option with your own directory. That way the exports file is correctly generated and installed.

You cannot simply point to the location where you have a checked out copy of libcifpp. That's not how this is intended to be used.

BTW, I get the impression you're using regular makefiles (based on previous questions you had). May I suggest switching to cmake? It is an investment but certainly worth the time. cmake will also pick up the correct location of all files and libraries, even if you have a system wide version installed and want to use a private copy.

**Comment by martin-s-a** [comment]
I am actually using the cmake commands provided by the readme file to compile and install the library (with minor minor tweaks, installing the library inside it's `build` directory instead of `$HOME./local`, because I want to contain the usage of this instance of the library to a single software project, and adding flag -DBUILD_SHARED_LIBS=ON to that command to produce a .so file instead of a .a so it can be used as a shared library inside the project).

Maybe later some makefile is being used to compile other cpp files and linked to the library, but that I have no control over, this is part of [Xmipp](https://github.com/I2PC/xmipp/tree/ms_feature_readC), which is a huge codebase that would need an important refactor to deal with that, and I don't think it's nearly at my reach right now.

Regarding the install location and how does it affect the usage, I made a test installing the latest version in a different folder:
`/home/msalinas/Documents/standalone-installations/libcifpp/`

There, I ran the following commands:
```
git clone https://github.com/PDB-REDO/libcifpp.git
cd libcifpp
cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/home/msalinas/Documents/standalone-installations/libcifpp/ -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
cmake --build build
cmake --install build
```
The library successfully installs in `/home/msalinas/Documents/standalone-installations/libcifpp/build`.

I also have a `test.cpp` file in `/home/msalinas/Documents/standalone-installations/`, as well as a makefile.
The test file imports the library using relative paths. Specifically, I have two import lines, one for the libcifpp instance in `/home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/`, and the other one in `/home/msalinas/Documents/standalone-installations/libcifpp/` (I leave one of the commented to test how does compiling work with the other one).

So, with that, I added two commands in the makefile. One of them, executes the following line:
```
g++ -Wall -Wextra -g -pthread -I/home/msalinas/Documents/standalone-installations/libcifpp/include test.cpp -o test -L/home/msalinas/Documents/standalone-installations/libcifpp/build -lcifpp -lz
```
while the other runs:
```
g++ -Wall -Wextra -g -pthread -I/home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/include test.cpp -o test -L/home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/build -lcifpp -lz
```

They both seem to work just fine when the proper `#include` statement is active in the cpp file. However, there must be somehow something different in how things are compiled in the xmipp project, because that error appears when compiling after having run this installation commands:
```
cd /home/msalinas/Documents/standalone-installations/xmipp/
git clone https://github.com/PDB-REDO/libcifpp.git src/libcifpp
cd libcifpp
cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/ -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
cmake --build build
cmake --install build
```
Which should pretty much be equivalent to the standalone version. In fact, running `tree` command on both libcifpp directories returns the same output.

However, I then changed all include paths in xmipp's instance to be relative to the file including. That means, if file `cif++/pdb/tls.hpp` wants to import file `cif++/datablock.hpp`, the include path should be `"../datablock.hpp"`, and then no errors appeared while compiling.

I tried migrating those changes to the standalone instance, reinstalling with the new header includes, and compiling again, which also resulted in no errors.

So, even if I'm not sure what is going on exactly that differs in usage between projects, as I am not able to effectively modify how xmipp compiles it's binaries linking external libraries, and using the relative path to the file importing instead of the `include/` folder works in both scenarios, I would recommend using that, unless there's something else I don't know about, in which case, feel free to let me know, of course.

**Comment by mhekkel** [comment]
When I suggested to use cmake, I meant to use it in your own project instead of what you were using. But I understand that is not an option.

Installing in a different location should not be a problem. I just tried this:

```bash
cd ~/projects/libcifpp/
cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/tmp/x -DBUILD_SHARED_LIBS=ON
cmake --build build -j
cmake --install build
cd /tmp/
cp ~/projects/libcifpp/examples/example.cpp .
cp ~/projects/libcifpp/examples/1cbs.cif.gz .
g++ example.cpp -I /tmp/x/include -L /tmp/x/lib -lcifpp
LD_LIBRARY_PATH=/tmp/x/lib ./a.out
```

And that works. No need to change any include. The example.cpp file contains `#include <cif++.hpp>` but works equally well with `#include "cif++.hpp"`

BTW, the reason exports.hpp is generated at install time is because the contents depend on the platform you're using as well as whether you use shared or static libraries.

**Comment by martin-s-a** [comment]
Yes, I've tried that too, and works well for me either, what I don't know is why does it work, even without the `LD_LIBRARY_PATH=/tmp/x/lib` in the `LD_LIBRARY_PATH=/tmp/x/lib a.out` command.

I'm new to C++ and I've never had to use an external non-standard library in a project before, so sorry if I don't understand some of the basics.

As far as I know, `#include <cif++.hpp>` looks for `cif++.hpp` in the system defined directories, such as `/usr/local/include`, or `/usr/include`, while `#include "cif++.hpp"` first looks for the file in the same directory as the file importing it, and, if not found, then on the same directories as the previous method, and that's why it's always a good idea to use the `" "` format when writing a library.

Following that logic, makes sense that, if my file `./cif++/pdb/tls.hpp` wants to include another file from the same lib `./cif++/datablock.hpp`, has to look for it using `#include "../datablock.hpp"`. What I don't know is, why in some scenarios, using `#include "cif++/datablock.hpp"` works, as if the file importing was in the root of the `include/` directory. In those same scenarios, the relative path option will work well, so to me it looks like the better option if it is always going to work no matter what.

I guess, when compiling xmipp, it should work too with the `#include "cif++/datablock.hpp"` format, but there must be something different in how xmipp compiles the libraries, although the installation commands of libcifpp are correct.

I have attached the output log of the compilation, just in case you are able to spot something different in the installation or compile process in regards of libcifpp.

```
Scipion v3.0.12 - Eugenius

 >>> WARNING: Image library not found!
  > Please install Xmipp to get full functionality. 
(Configuration->Plugins->scipion-em-xmipp -> expand, in Scipion plugin manager window)


 'xmipp.conf' detected.
Checking configuration ------------------------------
 'xmipp.conf' is already checked. Set VERIFIED=False to have it re-checked
Getting Dependencies -------------------------------------
 Checkouting cuFFTAdvisor:master ...
Already up to date.
 Checkouting CTPL:master ...
 git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
 Checkouting libsvm:master ...
Already up to date.
 Checkouting libcifpp:trunk ...
Already up to date.
Getting sources -------------------------------------
 Checkouting xmippCore:devel ...
Already up to date.
 Checkouting xmippViz:tags/v3.23.03-Kratos ...
Already up to date.
 Checkouting scipion-em-xmipp:devel ...
Already up to date.
 Checkouting xmipp:ms_feature_readCIF ...
Already up to date.
Building Dependencies -------------------------------------
 make all
mkdir -p build/
nvcc --cudart static -shared -link -Wno-deprecated-gpu-targets -o build/libcuFFTAdvisor.so obj/advisor.o obj/benchmarker.o obj/benchmarkResult.o obj/cudaAsserts.o obj/generalTransform.o obj/inputParser.o obj/main.o obj/sizeOptimizer.o obj/transform.o obj/transformGenerator.o obj/validator.o
mkdir -p build/
nvcc -o build/cuFFTAdvisor obj/advisor.o obj/benchmarker.o obj/benchmarkResult.o obj/cudaAsserts.o obj/generalTransform.o obj/inputParser.o obj/main.o obj/sizeOptimizer.o obj/transform.o obj/transformGenerator.o obj/validator.o -lcufft -Wno-deprecated-gpu-targets
 cp src/cuFFTAdvisor/build/libcuFFTAdvisor.so src/xmipp/lib/
 make lib
if [ "Linux" = "Darwin" ]; then \
	SHARED_LIB_FLAG="-dynamiclib -Wl,-install_name,libsvm.so"; \
else \
	SHARED_LIB_FLAG="-shared -Wl,-soname,libsvm.so"; \
fi; \
g++ ${SHARED_LIB_FLAG} svm.o -o libsvm.so
 cp src/libsvm/libsvm.so src/xmipp/lib
 cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/ -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
Not trying to recreate symop_table_data.hpp since CCP4 is not defined
-- Testing for known regex bug, since you're using GNU libstdc++
-- You are probably trying to compile using the g++ standard library which contains a crashing std::regex implementation. Will use boost::regex instead
-- Configuring done
-- Generating done
-- Build files have been written to: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/build
 cmake --build build
Consolidate compiler generated dependencies of target cifpp
[  4%] Building CXX object CMakeFiles/cifpp.dir/src/utilities.cpp.o
[  9%] Linking CXX shared library libcifpp.so
[100%] Built target cifpp
[100%] Built target COMPONENTS
 cmake --install build
-- Install configuration: "Release"
-- Installing: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/lib/libcifpp.so.5.0.9
-- Up-to-date: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/lib/libcifpp.so.5
-- Up-to-date: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/lib/libcifpp.so
-- Up-to-date: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/lib/cmake/cifpp/cifppTargets.cmake
-- Up-to-date: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/lib/cmake/cifpp/cifppTargets-release.cmake
-- Up-to-date: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/include/cif++/exports.hpp
-- Up-to-date: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/share/libcifpp/mmcif_ddl.dic
-- Up-to-date: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/share/libcifpp/mmcif_pdbx.dic
-- Up-to-date: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/share/libcifpp/mmcif_ma.dic
-- Up-to-date: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/share/libcifpp/components.cif
-- Up-to-date: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/lib/cmake/cifpp/cifppConfig.cmake
-- Up-to-date: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/lib/cmake/cifpp/cifppConfigVersion.cmake
-- Up-to-date: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/lib/pkgconfig/libcifpp.pc
-- Up-to-date: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/etc/cron.weekly/update-libcifpp-data
-- Up-to-date: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/var/cache/libcifpp
-- Up-to-date: /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/etc/libcifpp/cache-update.d
 cp src/libcifpp/lib/libcifpp.so* src/xmipp/lib
Compiling -------------------------------------------
 /usr/bin/env python3 $(which scons) -j8
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `lib/libXmippCore.so' is up to date.
scons: `lib/xmippCore.so' is up to date.
scons: done building targets.
 /usr/bin/env python3 $(which scons) -j8
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `lib/libXmipp.so' is up to date.
scons: `lib/_swig_frm.so' is up to date.
scons: `lib/libXmippCuda.a' is up to date.
scons: `lib/libXmippInterfaceCuda.so' is up to date.
mpicxx -o lib/libXmippParallelCuda.so -flto -L/usr/local/cuda-11.7/lib64 -L/usr/local/cuda-11.7/lib64/stubs -L/home/msalinas/Documents/miniconda/envs/scipion3/lib -L/usr/lib/x86_64-linux-gnu/hdf5/serial -shared libraries/parallel_adapt_cuda/mpi_reconstruct_fourier_gpu.os -L/home/msalinas/Documents/standalone-installations/xmipp/src/xmippCore/lib -Llib -L/home/msalinas/Documents/miniconda/envs/scipion3/lib -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lXmipp -lXmippInterfaceCuda -lXmippCuda -lcudart -lcufft -lnvidia-ml -lcuFFTAdvisor
scons: `lib/libXmippParallel.so' is up to date.
scons: `bin/xmipp_resolution_directional' is up to date.
scons: `bin/xmipp_pdb_label_from_volume' is up to date.
scons: `bin/xmipp_tomo_extract_particlestacks' is up to date.
mpicxx -o bin/xmipp_mpi_performance_test applications/programs/mpi_performance_test/mpi_performance_test_main.o -L/home/msalinas/Documents/standalone-installations/xmipp/src/xmippCore/lib -Llib -Llib -L/home/msalinas/Documents/miniconda/envs/scipion3/lib -L/usr/lib/x86_64-linux-gnu/hdf5/serial -L/home/msalinas/Documents/standalone-installations/xmipp/build/lib -L/home/msalinas/Documents/standalone-installations/xmipp/build/bindings/python -L/home/msalinas/Documents/miniconda/envs/scipion3/lib -L/home/msalinas/Documents/scipion/software/lib -lXmipp -lhdf5 -lhdf5_cpp -lfftw3 -lfftw3_threads -ljpeg -ltiff -lfftw3f -lfftw3f_threads -lpython3.8 -lpthread -lsvm -lcifpp -lXmippCore -lXmippParallel
scons: `bin/xmipp_image_residuals' is up to date.
scons: `bin/xmipp_reconstruct_art' is up to date.
scons: `bin/xmipp_transform_mirror' is up to date.
scons: `bin/xmipp_transform_randomize_phases' is up to date.
scons: `bin/xmipp_forward_zernike_volume' is up to date.
scons: `bin/xmipp_metadata_import' is up to date.
scons: `bin/xmipp_phantom_simulate_microscope' is up to date.
scons: `bin/xmipp_compare_views' is up to date.
scons: `bin/xmipp_metadata_xml' is up to date.
scons: `bin/xmipp_validation_nontilt' is up to date.
mpicxx -o bin/xmipp_mpi_classify_CLTomo_prog applications/programs/mpi_classify_CLTomo_prog/mpi_classify_CLTomo_prog_main.o -L/home/msalinas/Documents/standalone-installations/xmipp/src/xmippCore/lib -Llib -Llib -L/home/msalinas/Documents/miniconda/envs/scipion3/lib -L/usr/lib/x86_64-linux-gnu/hdf5/serial -L/home/msalinas/Documents/standalone-installations/xmipp/build/lib -L/home/msalinas/Documents/standalone-installations/xmipp/build/bindings/python -L/home/msalinas/Documents/miniconda/envs/scipion3/lib -L/home/msalinas/Documents/scipion/software/lib -lpython3.8 -lXmipp -lhdf5 -lhdf5_cpp -lfftw3 -lfftw3_threads -ljpeg -ltiff -lfftw3f -lfftw3f_threads -lpython3.8 -lpthread -lsvm -lcifpp -lXmippCore -lXmippParallel
mpicxx -o bin/xmipp_mpi_transform_geometry applications/programs/mpi_transform_geometry/mpi_transform_geometry_main.o -L/home/msalinas/Documents/standalone-installations/xmipp/src/xmippCore/lib -Llib -Llib -L/home/msalinas/Documents/miniconda/envs/scipion3/lib -L/usr/lib/x86_64-linux-gnu/hdf5/serial -L/home/msalinas/Documents/standalone-installations/xmipp/build/lib -L/home/msalinas/Documents/standalone-installations/xmipp/build/bindings/python -L/home/msalinas/Documents/miniconda/envs/scipion3/lib -L/home/msalinas/Documents/scipion/software/lib -lXmipp -lhdf5 -lhdf5_cpp -lfftw3 -lfftw3_threads -ljpeg -ltiff -lfftw3f -lfftw3f_threads -lpython3.8 -lpthread -lsvm -lcifpp -lXmippCore -lXmippParallel
scons: `bin/xmipp_angular_distribution_show' is up to date.
scons: `bin/xmipp_transform_center_image' is up to date.
mpicxx -o bin/xmipp_mpi_classify_CL2D applications/programs/mpi_classify_CL2D/mpi_classify_CL2D_main.o -L/home/msalinas/Documents/standalone-installations/xmipp/src/xmippCore/lib -Llib -Llib -L/home/msalinas/Documents/miniconda/envs/scipion3/lib -L/usr/lib/x86_64-linux-gnu/hdf5/serial -L/home/msalinas/Documents/standalone-installations/xmipp/build/lib -L/home/msalinas/Documents/standalone-installations/xmipp/build/bindings/python -L/home/msalinas/Documents/miniconda/envs/scipion3/lib -L/home/msalinas/Documents/scipion/software/lib -lXmipp -lhdf5 -lhdf5_cpp -lfftw3 -lfftw3_threads -ljpeg -ltiff -lfftw3f -lfftw3f_threads -lpython3.8 -lpthread -lsvm -lcifpp -lXmippCore -lXmippParallel
scons: `bin/xmipp_micrograph_automatic_picking' is up to date.
scons: `bin/xmipp_parallel_forward_art_zernike3d' is up to date.
scons: `bin/xmipp_pdb_nma_deform' is up to date.
scons: `bin/xmipp_classify_kmeans_2d' is up to date.
scons: `bin/xmipp_transform_mask' is up to date.
mpicxx -o applications/programs/mpi_angular_project_library/mpi_angular_project_library_main.o -c -mtune=native -march=native -flto -std=c++17 -O3 -Iexternal -Ilibraries -I/home/msalinas/Documents/standalone-installations/xmipp/src/xmippCore -I/home/msalinas/Documents/standalone-installations/xmipp/src -I/home/msalinas/Documents/miniconda/envs/scipion3/include -I/usr/include/hdf5/serial applications/programs/mpi_angular_project_library/mpi_angular_project_library_main.cpp
scons: `bin/xmipp_angular_continuous_assign2' is up to date.
scons: `bin/xmipp_angular_continuous_assign' is up to date.
scons: `bin/xmipp_flexible_alignment' is up to date.
/usr/bin/g++ -o bin/xmipp_cuda_angular_sph_alignment -flto -L/usr/local/cuda-11.7/lib64 -L/usr/local/cuda-11.7/lib64/stubs applications/programs/cuda_angular_sph_alignment/cuda_angular_sph_alignment_main.o -L/home/msalinas/Documents/standalone-installations/xmipp/src/xmippCore/lib -Llib -Llib -L/home/msalinas/Documents/miniconda/envs/scipion3/lib -L/usr/lib/x86_64-linux-gnu/hdf5/serial -L/home/msalinas/Documents/standalone-installations/xmipp/build/lib -L/home/msalinas/Documents/standalone-installations/xmipp/build/bindings/python -L/home/msalinas/Documents/miniconda/envs/scipion3/lib -L/home/msalinas/Documents/scipion/software/lib -lXmipp -lhdf5 -lhdf5_cpp -lfftw3 -lfftw3_threads -ljpeg -ltiff -lfftw3f -lfftw3f_threads -lpython3.8 -lpthread -lsvm -lcifpp -lXmippCore -lXmippInterfaceCuda -lXmippCuda -lcuFFTAdvisor -lcudart -lcufft -lnvidia-ml -lpthread
/usr/bin/g++ -o bin/xmipp_tomo_confidence_map -flto applications/programs/tomo_confidence_map/tomo_confidence_map.o -L/home/msalinas/Documents/standalone-installations/xmipp/src/xmippCore/lib -Llib -Llib -L/home/msalinas/Documents/miniconda/envs/scipion3/lib -L/usr/lib/x86_64-linux-gnu/hdf5/serial -L/home/msalinas/Documents/standalone-installations/xmipp/build/lib -L/home/msalinas/Documents/standalone-installations/xmipp/build/bindings/python -L/home/msalinas/Documents/miniconda/envs/scipion3/lib -L/home/msalinas/Documents/scipion/software/lib -lXmipp -lhdf5 -lhdf5_cpp -lfftw3 -lfftw3_threads -ljpeg -ltiff -lfftw3f -lfftw3f_threads -lpython3.8 -lpthread -lsvm -lcifpp -lXmippCore
In file included from /home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/include/cif++.hpp:29,
                 from libraries/data/pdb.h:33,
                 from libraries/reconstruction/project.h:32,
                 from libraries/reconstruction/angular_project_library.h:41,
                 from libraries/parallel/mpi_angular_project_library.cpp:38,
                 from applications/programs/mpi_angular_project_library/mpi_angular_project_library_main.cpp:28:
/home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/include/cif++/utilities.hpp:29:10: fatal error: cif++/exports.hpp: No such file or directory
   29 | #include "cif++/exports.hpp"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
scons: *** [applications/programs/mpi_angular_project_library/mpi_angular_project_library_main.o] Error 1
scons: building terminated because of errors.
 
'cif++/exports.hpp' file not found.
 
Some error occurred during the compilation of 'xmipp' ('applications/programs/mpi_angular_project_library/mpi_angular_project_library_main.o').

Traceback (most recent call last):
  File "/home/msalinas/Documents/miniconda/envs/scipion3/bin/emprogram", line 8, in <module>
    sys.exit(main())
  File "/home/msalinas/Documents/miniconda/envs/scipion3/lib/python3.8/site-packages/pwem/cmd/program.py", line 43, in main
    runProgram(program, params)
  File "/home/msalinas/Documents/miniconda/envs/scipion3/lib/python3.8/site-packages/pwem/utils.py", line 73, in runProgram
    pwutils.runJob(None, program, params, env=env)
  File "/home/msalinas/Documents/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 55, in runJob
    return runCommand(command, env, cwd)
  File "/home/msalinas/Documents/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 70, in runCommand
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
  File "/home/msalinas/Documents/miniconda/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' ./xmipp ' returned non-zero exit status 1.
```

**Comment by mhekkel** [comment]
LD_LIBRARY_PATH=/tmp/x/lib a.out

Since I didn't specify a name for the output of the compiler, the default is used: a.out. And since the shared library is installed in a non-standard location, I need to specify the location of the shared library before I can run the application.

About including files, yes, if the include is specified using quotes ("") then the 'user' directories are search. If the include is specified using <>, only the system paths are searched.

Searching is done simply by appending the specified path to one of the user or system paths. First match wins. So if you include cif++/datablock.hpp and the include path contains /tmp/x/include where I installed libcifpp, then the file is found as /tmp/x/include/cif++/datablock.hpp.

Beware that if you use a name for a local file that is the same as a system header file, your local file is 'found', unless you specify the include using <> delimiters.

Now to your compilation problem. I've never used scons, but I do know by looking at it, you will have to specify the path to the include files for libcifpp in scons for your project. E.g. this line:

```
mpicxx -o applications/programs/mpi_angular_project_library/mpi_angular_project_library_main.o -c -mtune=native -march=native -flto -std=c++17 -O3 -Iexternal -Ilibraries -I/home/msalinas/Documents/standalone-installations/xmipp/src/xmippCore -I/home/msalinas/Documents/standalone-installations/xmipp/src -I/home/msalinas/Documents/miniconda/envs/scipion3/include -I/usr/include/hdf5/serial applications/programs/mpi_angular_project_library/mpi_angular_project_library_main.cpp
```

has several include paths added: each one is preceded by a -I. There is no include path specified for libcifpp. And that's why your code cannot find the cif++ include files.

So you will have to dive into the Scons configuration files to find a place where you can add the correct path.

**Comment by martin-s-a** [comment]
Thanks for the explanation, helps a lot!

So, if I understood correctly, if you add the custom include folder to the system library paths, you sould have no issues using the `#include "cif++/datablock.hpp"` format, and I guess that `#include "datablock.hpp"` would work anyway, since it is using the path relative to the file with the include sentence.

About the installation log, I'm sorry, I just realised the include path to libcifpp is missing because this log was a re-run of the same command, so it was sometimes found in the now `... is up to date` message, since they don't need recompiling. I initially did this because I wanted to dump the contents of the install output into a file, but when run from a fresh start, require some user interaction so the file wouldn't have been properly filled. I'll just copy it directly from the terminal instead.

This log file contains the original output where all compilation commands are shown (apologies in advance, the output log is huge, but you don't need to look through all of it):
```
[compile.log](https://github.com/PDB-REDO/libcifpp/files/11181656/compile.log)
```
You can see that in many lines, like this one:
```bash
/usr/bin/g++ -o external/condor/CNLSolver.os -c -mtune=native -march=native -flto -std=c++17 -O3 -I../ -I/home/msalinas/Documents/miniconda/envs/scipion3/include -I/usr/include/hdf5/serial -fPIC -I/home/msalinas/Documents/miniconda/envs/scipion3/include/python3.8 -I/home/msalinas/Documents/miniconda/envs/scipion3/lib/python3.8/site-packages/numpy/core/include -Iexternal -Ilibraries -I/home/msalinas/Documents/standalone-installations/xmipp/src/xmippCore -I/home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/include external/condor/CNLSolver.cpp
```
The path to the include directory is being properly added, which is something that happens dinamically.
But then, there are others (the ones causing the error), where the path is missing, which explains the error:
```bash
mpicxx -o applications/programs/mpi_angular_project_library/mpi_angular_project_library_main.o -c -mtune=native -march=native -flto -std=c++17 -O3 -Iexternal -Ilibraries -I/home/msalinas/Documents/standalone-installations/xmipp/src/xmippCore -I/home/msalinas/Documents/standalone-installations/xmipp/src -I/home/msalinas/Documents/miniconda/envs/scipion3/include -I/usr/include/hdf5/serial applications/programs/mpi_angular_project_library/mpi_angular_project_library_main.cpp
```
If I change the includes in all of those files to the format I proposed, the compilation completes successfully.

Additionally, I just made a test where the same `test.cpp` I was compiling before was now being compiled removing the library path in the include flag (`-I/home/msalinas/Documents/standalone-installations/xmipp/src/libcifpp/include`), and the same problem I am seeing in xmipp's compilation showed up: works only with relative paths to file including. So you were right all this time about that flag missing somewhere in my compile commands. However, changing the include format to mine still worked fine as if I added the -I flag with the include path, when I didn't.

So, as a last question for now (sorry about it, I have taken a lot of time from you), why is it better to use the `#include "cif++/exports.hpp"` format rather than the `#include "exports.hpp"` format? In my lack of knowledge, it seems like the first one only works correctly if you link properly the include folder when compiling, while the last one works no matter what.

**Comment by mhekkel** [comment]
Op 07-04-2023 om 23:46 schreef Martin Salinas:
> why is it better to use the |#include "cif++/exports.hpp"| format 
> rather than the |#include "exports.hpp"| format? 

You might have a file called exports.hpp in your project and 
accidentally include the wrong one.

Besides, it is a matter of style, this way you explicitly specify the 
exports.hpp file from the cif++ project.

**Comment by martin-s-a** [comment]
I finally was able to find it and fix it. Thanks for your help!

**Pull request merged**
